os:
- linux
- osx

language: php

php:
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
    - composer install --prefer-dist --dev
    - phpenv rehash

notifications:
  email: false
