os:
- linux

language: php

cache:
  directories:
  - $HOME/.phive

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.0snapshot
  - 7.1snapshot
  - 7.2snapshot
  - master

before_install:
  - wget https://phar.io/releases/phive.phar
  - wget https://phar.io/releases/phive.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/bin/phive

before_script:
  - composer install --prefer-source --no-interaction --dev
  - phive --no-progress install --trust-gpg-keys 4AA394086372C20A,2A8299CE842DD38C
  - ant phpab

script: ./tools/phpunit

matrix:
  allow_failures:
    - php: master
  fast_finish: true

notifications:
  email: false
